"""add coldness

Revision ID: f0d89367cd54
Revises: 24dfd0eb9da6
Create Date: 2020-02-16 19:24:40.144498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d89367cd54'
down_revision = '24dfd0eb9da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'icon')
    # ### end Alembic commands ###
